# Generated by Django 3.2.8 on 2023-05-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='image',
            field=models.ImageField(default='../templates/images/q.gif', null=True, upload_to='../templates/images/'),
        ),
    ]
