# Generated by Django 3.2.8 on 2023-05-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_mainmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
